<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class AmenitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('amenities')->insert([
            [
                'id' => 1,
                'sync_id' => 1,
                'amenity_category_id' => 1,
                'name' => 'Агааржуулах систем',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 2,
                'sync_id' => 2,
                'amenity_category_id' => 1,
                'name' => 'Тагт',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 3,
                'sync_id' => 3,
                'amenity_category_id' => 1,
                'name' => 'Ванн',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 4,
                'sync_id' => 4,
                'amenity_category_id' => 1,
                'name' => 'Үзэгдэх орчин',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 5,
                'sync_id' => 5,
                'amenity_category_id' => 1,
                'name' => 'Хавтгай дэлгэцтэй зурагт',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 6,
                'sync_id' => 6,
                'amenity_category_id' => 1,
                'name' => 'Хувийн ариун цэврийн өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 7,
                'sync_id' => 7,
                'amenity_category_id' => 1,
                'name' => 'Террас',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 8,
                'sync_id' => 8,
                'amenity_category_id' => 1,
                'name' => 'Ус буцалгагч',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 9,
                'sync_id' => 9,
                'amenity_category_id' => 1,
                'name' => 'Спа',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 10,
                'sync_id' => 10,
                'amenity_category_id' => 1,
                'name' => 'Тамхи татаж болно',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 11,
                'sync_id' => 11,
                'amenity_category_id' => 1,
                'name' => 'Тамхи татахыг хориглоно',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 12,
                'sync_id' => 12,
                'amenity_category_id' => 2,
                'name' => 'Хүүхдийн ор',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 13,
                'sync_id' => 13,
                'amenity_category_id' => 2,
                'name' => 'Хувцасны өлгүүр',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 14,
                'sync_id' => 14,
                'amenity_category_id' => 2,
                'name' => 'Хувцас хатаах тавиур',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 15,
                'sync_id' => 15,
                'amenity_category_id' => 2,
                'name' => 'Эвхэгддэг ор',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 16,
                'sync_id' => 16,
                'amenity_category_id' => 2,
                'name' => 'Буйдан',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 17,
                'sync_id' => 17,
                'amenity_category_id' => 2,
                'name' => 'Хогийн сав',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 18,
                'sync_id' => 18,
                'amenity_category_id' => 2,
                'name' => 'Халуун усан сан',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 19,
                'sync_id' => 19,
                'amenity_category_id' => 2,
                'name' => 'Infinity Pool',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 20,
                'sync_id' => 20,
                'amenity_category_id' => 2,
                'name' => 'Plunge Pool',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 21,
                'sync_id' => 21,
                'amenity_category_id' => 2,
                'name' => 'Pool Cover',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 22,
                'sync_id' => 22,
                'amenity_category_id' => 2,
                'name' => 'Pool Towels',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 23,
                'sync_id' => 23,
                'amenity_category_id' => 2,
                'name' => 'Pool With a View',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 24,
                'sync_id' => 24,
                'amenity_category_id' => 2,
                'name' => 'Хатаагч / сэнс',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 25,
                'sync_id' => 25,
                'amenity_category_id' => 2,
                'name' => 'Хувцасны шүүгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 26,
                'sync_id' => 26,
                'amenity_category_id' => 2,
                'name' => 'Хивс',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 27,
                'sync_id' => 27,
                'amenity_category_id' => 2,
                'name' => 'Walk-in closet',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 28,
                'sync_id' => 28,
                'amenity_category_id' => 2,
                'name' => 'Нэмэлт урт ор (> 198 см)',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 29,
                'sync_id' => 29,
                'amenity_category_id' => 2,
                'name' => 'Сэнс',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 30,
                'sync_id' => 30,
                'amenity_category_id' => 2,
                'name' => 'Задгай зуух',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 31,
                'sync_id' => 31,
                'amenity_category_id' => 2,
                'name' => 'Халаагуур',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 32,
                'sync_id' => 32,
                'amenity_category_id' => 2,
                'name' => 'Interconnecting room(s) available',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 33,
                'sync_id' => 33,
                'amenity_category_id' => 2,
                'name' => 'Индүү',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 34,
                'sync_id' => 34,
                'amenity_category_id' => 2,
                'name' => 'Индүүдэхэд хэрэгтэй бусад хэрэгсэл',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 35,
                'sync_id' => 35,
                'amenity_category_id' => 2,
                'name' => 'Халуун усны онгоц',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 36,
                'sync_id' => 36,
                'amenity_category_id' => 2,
                'name' => 'Шумуулны тор',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 37,
                'sync_id' => 37,
                'amenity_category_id' => 2,
                'name' => 'Сейф',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 38,
                'sync_id' => 38,
                'amenity_category_id' => 2,
                'name' => 'Буйдан',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 39,
                'sync_id' => 39,
                'amenity_category_id' => 2,
                'name' => 'Дууны хамгаалалттай',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 40,
                'sync_id' => 40,
                'amenity_category_id' => 2,
                'name' => 'Суух талбай',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 41,
                'sync_id' => 41,
                'amenity_category_id' => 2,
                'name' => 'Хавтан / гантиг шал',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 42,
                'sync_id' => 42,
                'amenity_category_id' => 2,
                'name' => 'Хослол хадгалах индүүдэх',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 43,
                'sync_id' => 43,
                'amenity_category_id' => 2,
                'name' => 'Угаалгын машин',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 44,
                'sync_id' => 44,
                'amenity_category_id' => 2,
                'name' => 'Хатуу мод / паркетан шал',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 45,
                'sync_id' => 45,
                'amenity_category_id' => 2,
                'name' => 'Ширээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 46,
                'sync_id' => 46,
                'amenity_category_id' => 2,
                'name' => 'Цэвэрлэгээний бүтээгдэхүүн',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 47,
                'sync_id' => 47,
                'amenity_category_id' => 2,
                'name' => 'Орны ойролцоо залгуур',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 48,
                'sync_id' => 48,
                'amenity_category_id' => 2,
                'name' => 'Адаптер',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 49,
                'sync_id' => 49,
                'amenity_category_id' => 2,
                'name' => 'Дэр',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 50,
                'sync_id' => 50,
                'amenity_category_id' => 2,
                'name' => 'Ариун цэврийн өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 51,
                'sync_id' => 51,
                'amenity_category_id' => 2,
                'name' => 'Нийтийн угаалгын өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 52,
                'sync_id' => 52,
                'amenity_category_id' => 2,
                'name' => 'Ариун цэврийн цаас',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 53,
                'sync_id' => 53,
                'amenity_category_id' => 2,
                'name' => 'Бидет',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 54,
                'sync_id' => 54,
                'amenity_category_id' => 2,
                'name' => 'Ванн эсвэл шүршүүр',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 55,
                'sync_id' => 55,
                'amenity_category_id' => 2,
                'name' => 'Халаат',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 56,
                'sync_id' => 56,
                'amenity_category_id' => 2,
                'name' => 'Үнэгүй ариун цэврийн өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 57,
                'sync_id' => 57,
                'amenity_category_id' => 2,
                'name' => 'Зочны ариун цэврийн өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 58,
                'sync_id' => 58,
                'amenity_category_id' => 2,
                'name' => 'Үс хатаагч',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 59,
                'sync_id' => 59,
                'amenity_category_id' => 2,
                'name' => 'Дундын бие засах газар',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 60,
                'sync_id' => 60,
                'amenity_category_id' => 2,
                'name' => 'Саун',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 61,
                'sync_id' => 61,
                'amenity_category_id' => 2,
                'name' => 'Шүршүүр',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 62,
                'sync_id' => 62,
                'amenity_category_id' => 2,
                'name' => 'Углааш',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 63,
                'sync_id' => 63,
                'amenity_category_id' => 2,
                'name' => 'Бие засах өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 64,
                'sync_id' => 64,
                'amenity_category_id' => 2,
                'name' => 'Нэмэлт угаалгын өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 65,
                'sync_id' => 65,
                'amenity_category_id' => 2,
                'name' => 'Шүдний оо / сойз',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 66,
                'sync_id' => 66,
                'amenity_category_id' => 2,
                'name' => 'Шампунь',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 67,
                'sync_id' => 67,
                'amenity_category_id' => 2,
                'name' => 'Ангижууруулагч',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 68,
                'sync_id' => 68,
                'amenity_category_id' => 2,
                'name' => 'Биений саван',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 69,
                'sync_id' => 69,
                'amenity_category_id' => 2,
                'name' => 'Шүршүүрийн малгай',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 70,
                'sync_id' => 70,
                'amenity_category_id' => 3,
                'name' => 'Компьютер',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 71,
                'sync_id' => 71,
                'amenity_category_id' => 3,
                'name' => 'Кабелийн сувгууд',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 72,
                'sync_id' => 72,
                'amenity_category_id' => 3,
                'name' => 'CD тоглуулагч',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 73,
                'sync_id' => 73,
                'amenity_category_id' => 3,
                'name' => 'DVD тоглуулагч',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 74,
                'sync_id' => 74,
                'amenity_category_id' => 3,
                'name' => 'Факс',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 75,
                'sync_id' => 75,
                'amenity_category_id' => 3,
                'name' => 'Зөөврийн компьютер аюулгүй',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 76,
                'sync_id' => 76,
                'amenity_category_id' => 3,
                'name' => 'Нэг үзвэрийн төлбөртэй суваг',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 77,
                'sync_id' => 77,
                'amenity_category_id' => 3,
                'name' => 'Радио',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 78,
                'sync_id' => 78,
                'amenity_category_id' => 3,
                'name' => 'Хиймэл дагуулын сувгууд',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 79,
                'sync_id' => 79,
                'amenity_category_id' => 3,
                'name' => 'Утас',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 80,
                'sync_id' => 80,
                'amenity_category_id' => 3,
                'name' => 'ТВ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 81,
                'sync_id' => 81,
                'amenity_category_id' => 4,
                'name' => 'Хоолны газар',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 82,
                'sync_id' => 82,
                'amenity_category_id' => 4,
                'name' => 'Хоолны ширээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 83,
                'sync_id' => 83,
                'amenity_category_id' => 4,
                'name' => 'Дарсны хундага',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 84,
                'sync_id' => 84,
                'amenity_category_id' => 4,
                'name' => 'Савтай ус',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 85,
                'sync_id' => 85,
                'amenity_category_id' => 4,
                'name' => 'Шоколад / жигнэмэг',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 86,
                'sync_id' => 86,
                'amenity_category_id' => 4,
                'name' => 'Жимс',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 87,
                'sync_id' => 87,
                'amenity_category_id' => 4,
                'name' => 'Дарс / оргилуун дарс',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 88,
                'sync_id' => 88,
                'amenity_category_id' => 4,
                'name' => 'Barbecue',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 89,
                'sync_id' => 89,
                'amenity_category_id' => 4,
                'name' => 'Зуух',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 90,
                'sync_id' => 90,
                'amenity_category_id' => 4,
                'name' => 'Цахилгаан зуух',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 91,
                'sync_id' => 91,
                'amenity_category_id' => 4,
                'name' => 'Талх шарагч',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 92,
                'sync_id' => 92,
                'amenity_category_id' => 4,
                'name' => 'Аяга таваг угаагч',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 93,
                'sync_id' => 93,
                'amenity_category_id' => 4,
                'name' => 'Гадаа хоолны газар',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 94,
                'sync_id' => 94,
                'amenity_category_id' => 4,
                'name' => 'Outdoor furniture',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 95,
                'sync_id' => 95,
                'amenity_category_id' => 4,
                'name' => 'Минибар',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 96,
                'sync_id' => 96,
                'amenity_category_id' => 4,
                'name' => 'Гал тогоо',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 97,
                'sync_id' => 97,
                'amenity_category_id' => 4,
                'name' => 'Бичил долгионы зуух',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 98,
                'sync_id' => 98,
                'amenity_category_id' => 4,
                'name' => 'Хөргөгч',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 99,
                'sync_id' => 99,
                'amenity_category_id' => 4,
                'name' => 'Цай / Кофе үйлдвэрлэгч',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 100,
                'sync_id' => 100,
                'amenity_category_id' => 4,
                'name' => 'Кофены машин',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 101,
                'sync_id' => 101,
                'amenity_category_id' => 4,
                'name' => 'High chair',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 102,
                'sync_id' => 102,
                'amenity_category_id' => 5,
                'name' => 'Картын түлхүүр',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 103,
                'sync_id' => 103,
                'amenity_category_id' => 5,
                'name' => 'Гал хамгаалагч',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 104,
                'sync_id' => 104,
                'amenity_category_id' => 5,
                'name' => 'Гал унтраагч',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 105,
                'sync_id' => 105,
                'amenity_category_id' => 5,
                'name' => 'Шүүгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 106,
                'sync_id' => 106,
                'amenity_category_id' => 5,
                'name' => 'Түлхүүр нэвтрэх',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 107,
                'sync_id' => 107,
                'amenity_category_id' => 5,
                'name' => 'Амралтын өрөөний эрх',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 108,
                'sync_id' => 108,
                'amenity_category_id' => 5,
                'name' => 'Сэрүүлэгтэй цаг',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 109,
                'sync_id' => 109,
                'amenity_category_id' => 5,
                'name' => 'Сэрэх үйлчилгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 110,
                'sync_id' => 110,
                'amenity_category_id' => 5,
                'name' => 'Үйлчилгээ / сэрүүлэг',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 111,
                'sync_id' => 111,
                'amenity_category_id' => 5,
                'name' => 'Даавуу',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 112,
                'sync_id' => 112,
                'amenity_category_id' => 5,
                'name' => 'Алчуур',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 113,
                'sync_id' => 113,
                'amenity_category_id' => 6,
                'name' => 'Хашаа н доторх',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 114,
                'sync_id' => 114,
                'amenity_category_id' => 6,
                'name' => 'Хотын үзэмж',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 115,
                'sync_id' => 115,
                'amenity_category_id' => 6,
                'name' => 'Цэцэрлэгийн үзэмж',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 116,
                'sync_id' => 116,
                'amenity_category_id' => 6,
                'name' => 'Нуурын үзэгдэх орчин',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 117,
                'sync_id' => 117,
                'amenity_category_id' => 6,
                'name' => 'Landmark view',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 118,
                'sync_id' => 118,
                'amenity_category_id' => 6,
                'name' => 'Уулын үзэмж',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 119,
                'sync_id' => 119,
                'amenity_category_id' => 6,
                'name' => 'Голын үзэгдэх орчин',
                'is_default' => 0,
                'is_most' => 0,
            ],
            // [
            //     'id' => ,
            //     'sync_id' => ,
            //     'amenity_category_id' => 1,
            //     'name' => '',
            //     'is_default' => 0,
            //     'is_most' => 0,
            // ],
        ]);

        DB::table('amenity_translations')->insert([
            [
                'id' => 1,
                'sync_id' => 1,
                'locale' => 'en',
                'translation_id' => 1,
                'name' => 'Air conditioning',
            ],
            [
                'id' => 2,
                'sync_id' => 2,
                'locale' => 'en',
                'translation_id' => 2,
                'name' => 'Balcony',
            ],
            [
                'id' => 3,
                'sync_id' => 3,
                'locale' => 'en',
                'translation_id' => 3,
                'name' => 'Bathtub',
            ],
            [
                'id' => 4,
                'sync_id' => 4,
                'locale' => 'en',
                'translation_id' => 4,
                'name' => 'View',
            ],
            [
                'id' => 5,
                'sync_id' => 5,
                'locale' => 'en',
                'translation_id' => 5,
                'name' => 'Flat-screen TV',
            ],
            [
                'id' => 6,
                'sync_id' => 6,
                'locale' => 'en',
                'translation_id' => 6,
                'name' => 'Private bathroom',
            ],
            [
                'id' => 7,
                'sync_id' => 7,
                'locale' => 'en',
                'translation_id' => 7,
                'name' => 'Terrace',
            ],
            [
                'id' => 8,
                'sync_id' => 8,
                'locale' => 'en',
                'translation_id' => 8,
                'name' => 'Electric kettle',
            ],
            [
                'id' => 9,
                'sync_id' => 9,
                'locale' => 'en',
                'translation_id' => 9,
                'name' => 'Spa tub',
            ],
            [
                'id' => 10,
                'sync_id' => 10,
                'locale' => 'en',
                'translation_id' => 10,
                'name' => 'Smoking',
            ],
            [
                'id' => 11,
                'sync_id' => 11,
                'locale' => 'en',
                'translation_id' => 11,
                'name' => 'Non-Smoking',
            ],
            [
                'id' => 12,
                'sync_id' => 12,
                'locale' => 'en',
                'translation_id' => 12,
                'name' => "Childrens' cribs",
            ],
            [
                'id' => 13,
                'sync_id' => 13,
                'locale' => 'en',
                'translation_id' => 13,
                'name' => 'Clothes rack',
            ],
            [
                'id' => 14,
                'sync_id' => 14,
                'locale' => 'en',
                'translation_id' => 14,
                'name' => 'Drying rack for clothing',
            ],
            [
                'id' => 15,
                'sync_id' => 15,
                'locale' => 'en',
                'translation_id' => 15,
                'name' => 'Fold-up bed',
            ],
            [
                'id' => 16,
                'sync_id' => 16,
                'locale' => 'en',
                'translation_id' => 16,
                'name' => 'Sofa bed',
            ],
            [
                'id' => 17,
                'sync_id' => 17,
                'locale' => 'en',
                'translation_id' => 17,
                'name' => 'Trash cans',
            ],
            [
                'id' => 18,
                'sync_id' => 18,
                'locale' => 'en',
                'translation_id' => 18,
                'name' => 'Heated Pool',
            ],
            [
                'id' => 19,
                'sync_id' => 19,
                'locale' => 'en',
                'translation_id' => 19,
                'name' => 'Infinity Pool',
            ],
            [
                'id' => 20,
                'sync_id' => 20,
                'locale' => 'en',
                'translation_id' => 20,
                'name' => 'Plunge Pool',
            ],
            [
                'id' => 21,
                'sync_id' => 21,
                'locale' => 'en',
                'translation_id' => 21,
                'name' => 'Pool Cover',
            ],
            [
                'id' => 22,
                'sync_id' => 22,
                'locale' => 'en',
                'translation_id' => 22,
                'name' => 'Pool Towels',
            ],
            [
                'id' => 23,
                'sync_id' => 23,
                'locale' => 'en',
                'translation_id' => 23,
                'name' => 'Pool With a View',
            ],
            [
                'id' => 24,
                'sync_id' => 24,
                'locale' => 'en',
                'translation_id' => 24,
                'name' => 'Dryer',
            ],
            [
                'id' => 25,
                'sync_id' => 25,
                'locale' => 'en',
                'translation_id' => 25,
                'name' => 'Wardrobe/Closet',
            ],
            [
                'id' => 26,
                'sync_id' => 26,
                'locale' => 'en',
                'translation_id' => 26,
                'name' => 'Carpeted',
            ],
            [
                'id' => 27,
                'sync_id' => 27,
                'locale' => 'en',
                'translation_id' => 27,
                'name' => 'Walk-in closet',
            ],
            [
                'id' => 28,
                'sync_id' => 28,
                'locale' => 'en',
                'translation_id' => 28,
                'name' => 'Extra long beds (> 6.5 ft)',
            ],
            [
                'id' => 29,
                'sync_id' => 29,
                'locale' => 'en',
                'translation_id' => 29,
                'name' => 'Fan',
            ],
            [
                'id' => 30,
                'sync_id' => 30,
                'locale' => 'en',
                'translation_id' => 30,
                'name' => 'Fireplace',
            ],
            [
                'id' => 31,
                'sync_id' => 31,
                'locale' => 'en',
                'translation_id' => 31,
                'name' => 'Heating',
            ],
            [
                'id' => 32,
                'sync_id' => 32,
                'locale' => 'en',
                'translation_id' => 32,
                'name' => 'Interconnecting room(s) available',
            ],
            [
                'id' => 33,
                'sync_id' => 33,
                'locale' => 'en',
                'translation_id' => 33,
                'name' => 'Iron',
            ],
            [
                'id' => 34,
                'sync_id' => 34,
                'locale' => 'en',
                'translation_id' => 34,
                'name' => 'Ironing facilities',
            ],
            [
                'id' => 35,
                'sync_id' => 35,
                'locale' => 'en',
                'translation_id' => 35,
                'name' => 'Hot tub',
            ],
            [
                'id' => 36,
                'sync_id' => 36,
                'locale' => 'en',
                'translation_id' => 36,
                'name' => 'Mosquito net',
            ],
            [
                'id' => 37,
                'sync_id' => 37,
                'locale' => 'en',
                'translation_id' => 37,
                'name' => 'Safe',
            ],
            [
                'id' => 38,
                'sync_id' => 38,
                'locale' => 'en',
                'translation_id' => 38,
                'name' => 'Sofa',
            ],
            [
                'id' => 39,
                'sync_id' => 39,
                'locale' => 'en',
                'translation_id' => 39,
                'name' => 'Soundproof',
            ],
            [
                'id' => 40,
                'sync_id' => 40,
                'locale' => 'en',
                'translation_id' => 40,
                'name' => 'Sitting area',
            ],
            [
                'id' => 41,
                'sync_id' => 41,
                'locale' => 'en',
                'translation_id' => 41,
                'name' => 'Tile/Marble floor',
            ],
            [
                'id' => 42,
                'sync_id' => 42,
                'locale' => 'en',
                'translation_id' => 42,
                'name' => 'Suit press',
            ],
            [
                'id' => 43,
                'sync_id' => 43,
                'locale' => 'en',
                'translation_id' => 43,
                'name' => 'Washing machine',
            ],
            [
                'id' => 44,
                'sync_id' => 44,
                'locale' => 'en',
                'translation_id' => 44,
                'name' => 'Hardwood/Parquet floors',
            ],
            [
                'id' => 45,
                'sync_id' => 45,
                'locale' => 'en',
                'translation_id' => 45,
                'name' => 'Desk',
            ],
            [
                'id' => 46,
                'sync_id' => 46,
                'locale' => 'en',
                'translation_id' => 46,
                'name' => 'Cleaning products',
            ],
            [
                'id' => 47,
                'sync_id' => 47,
                'locale' => 'en',
                'translation_id' => 47,
                'name' => 'Socket near the bed',
            ],
            [
                'id' => 48,
                'sync_id' => 48,
                'locale' => 'en',
                'translation_id' => 48,
                'name' => 'Adapter',
            ],
            [
                'id' => 49,
                'sync_id' => 49,
                'locale' => 'en',
                'translation_id' => 49,
                'name' => 'Pillow',
            ],
            [
                'id' => 50,
                'sync_id' => 50,
                'locale' => 'en',
                'translation_id' => 50,
                'name' => 'Bathroom',
            ],
            [
                'id' => 51,
                'sync_id' => 51,
                'locale' => 'en',
                'translation_id' => 51,
                'name' => 'Shared bathroom',
            ],
            [
                'id' => 52,
                'sync_id' => 52,
                'locale' => 'en',
                'translation_id' => 52,
                'name' => 'Toilet paper',
            ],
            [
                'id' => 53,
                'sync_id' => 53,
                'locale' => 'en',
                'translation_id' => 53,
                'name' => 'Bidet',
            ],
            [
                'id' => 54,
                'sync_id' => 54,
                'locale' => 'en',
                'translation_id' => 54,
                'name' => 'Bathtub or shower',
            ],
            [
                'id' => 55,
                'sync_id' => 55,
                'locale' => 'en',
                'translation_id' => 55,
                'name' => 'Bathrobe',
            ],
            [
                'id' => 56,
                'sync_id' => 56,
                'locale' => 'en',
                'translation_id' => 56,
                'name' => 'Free toiletries',
            ],
            [
                'id' => 57,
                'sync_id' => 57,
                'locale' => 'en',
                'translation_id' => 57,
                'name' => 'Guest bathroom',
            ],
            [
                'id' => 58,
                'sync_id' => 58,
                'locale' => 'en',
                'translation_id' => 58,
                'name' => 'Hairdryer',
            ],
            [
                'id' => 59,
                'sync_id' => 59,
                'locale' => 'en',
                'translation_id' => 59,
                'name' => 'Shared toilet',
            ],
            [
                'id' => 60,
                'sync_id' => 60,
                'locale' => 'en',
                'translation_id' => 60,
                'name' => 'Sauna',
            ],
            [
                'id' => 61,
                'sync_id' => 61,
                'locale' => 'en',
                'translation_id' => 61,
                'name' => 'Shower',
            ],
            [
                'id' => 62,
                'sync_id' => 62,
                'locale' => 'en',
                'translation_id' => 62,
                'name' => 'Slippers',
            ],
            [
                'id' => 63,
                'sync_id' => 63,
                'locale' => 'en',
                'translation_id' => 63,
                'name' => 'Toilet',
            ],
            [
                'id' => 64,
                'sync_id' => 64,
                'locale' => 'en',
                'translation_id' => 64,
                'name' => 'Additional bathroom',
            ],
            [
                'id' => 65,
                'sync_id' => 65,
                'locale' => 'en',
                'translation_id' => 65,
                'name' => 'Toothbrush / Paste',
            ],
            [
                'id' => 66,
                'sync_id' => 66,
                'locale' => 'en',
                'translation_id' => 66,
                'name' => 'Shampoo',
            ],
            [
                'id' => 67,
                'sync_id' => 67,
                'locale' => 'en',
                'translation_id' => 67,
                'name' => 'Conditioner',
            ],
            [
                'id' => 68,
                'sync_id' => 68,
                'locale' => 'en',
                'translation_id' => 68,
                'name' => 'Body soap',
            ],
            [
                'id' => 69,
                'sync_id' => 69,
                'locale' => 'en',
                'translation_id' => 69,
                'name' => 'Shower cap',
            ],
            [
                'id' => 70,
                'sync_id' => 70,
                'locale' => 'en',
                'translation_id' => 70,
                'name' => 'Computer',
            ],
            [
                'id' => 71,
                'sync_id' => 71,
                'locale' => 'en',
                'translation_id' => 71,
                'name' => 'Cable channels',
            ],
            [
                'id' => 72,
                'sync_id' => 72,
                'locale' => 'en',
                'translation_id' => 72,
                'name' => 'CD Player',
            ],
            [
                'id' => 73,
                'sync_id' => 73,
                'locale' => 'en',
                'translation_id' => 73,
                'name' => 'DVD Player',
            ],
            [
                'id' => 74,
                'sync_id' => 74,
                'locale' => 'en',
                'translation_id' => 74,
                'name' => 'Fax',
            ],
            [
                'id' => 75,
                'sync_id' => 75,
                'locale' => 'en',
                'translation_id' => 75,
                'name' => 'Laptop safe',
            ],
            [
                'id' => 76,
                'sync_id' => 76,
                'locale' => 'en',
                'translation_id' => 76,
                'name' => 'Pay-per-view channels',
            ],
            [
                'id' => 77,
                'sync_id' => 77,
                'locale' => 'en',
                'translation_id' => 77,
                'name' => 'Radio',
            ],
            [
                'id' => 78,
                'sync_id' => 78,
                'locale' => 'en',
                'translation_id' => 78,
                'name' => 'Satellite channels',
            ],
            [
                'id' => 79,
                'sync_id' => 79,
                'locale' => 'en',
                'translation_id' => 79,
                'name' => 'Telephone',
            ],
            [
                'id' => 80,
                'sync_id' => 80,
                'locale' => 'en',
                'translation_id' => 80,
                'name' => 'TV',
            ],
            [
                'id' => 81,
                'sync_id' => 81,
                'locale' => 'en',
                'translation_id' => 81,
                'name' => 'Dining area',
            ],
            [
                'id' => 82,
                'sync_id' => 82,
                'locale' => 'en',
                'translation_id' => 82,
                'name' => 'Dining table',
            ],
            [
                'id' => 83,
                'sync_id' => 83,
                'locale' => 'en',
                'translation_id' => 83,
                'name' => 'Wine glasses',
            ],
            [
                'id' => 84,
                'sync_id' => 84,
                'locale' => 'en',
                'translation_id' => 84,
                'name' => 'Bottle of Water',
            ],
            [
                'id' => 85,
                'sync_id' => 85,
                'locale' => 'en',
                'translation_id' => 85,
                'name' => 'Chocolate/Cookies',
            ],
            [
                'id' => 86,
                'sync_id' => 86,
                'locale' => 'en',
                'translation_id' => 86,
                'name' => 'Fruit',
            ],
            [
                'id' => 87,
                'sync_id' => 87,
                'locale' => 'en',
                'translation_id' => 87,
                'name' => 'Wine/Champagne',
            ],
            [
                'id' => 88,
                'sync_id' => 88,
                'locale' => 'en',
                'translation_id' => 88,
                'name' => 'Barbecue',
            ],
            [
                'id' => 89,
                'sync_id' => 89,
                'locale' => 'en',
                'translation_id' => 89,
                'name' => 'Oven',
            ],
            [
                'id' => 90,
                'sync_id' => 90,
                'locale' => 'en',
                'translation_id' => 90,
                'name' => 'Stovetop',
            ],
            [
                'id' => 91,
                'sync_id' => 91,
                'locale' => 'en',
                'translation_id' => 91,
                'name' => 'Toaster',
            ],
            [
                'id' => 92,
                'sync_id' => 92,
                'locale' => 'en',
                'translation_id' => 92,
                'name' => 'Dishwasher',
            ],
            [
                'id' => 93,
                'sync_id' => 93,
                'locale' => 'en',
                'translation_id' => 93,
                'name' => 'Outdoor dining area',
            ],
            [
                'id' => 94,
                'sync_id' => 94,
                'locale' => 'en',
                'translation_id' => 94,
                'name' => 'Outdoor furniture',
            ],
            [
                'id' => 95,
                'sync_id' => 95,
                'locale' => 'en',
                'translation_id' => 95,
                'name' => 'Minibar',
            ],
            [
                'id' => 96,
                'sync_id' => 96,
                'locale' => 'en',
                'translation_id' => 96,
                'name' => 'Kitchen',
            ],
            [
                'id' => 97,
                'sync_id' => 97,
                'locale' => 'en',
                'translation_id' => 97,
                'name' => 'Microwave',
            ],
            [
                'id' => 98,
                'sync_id' => 98,
                'locale' => 'en',
                'translation_id' => 98,
                'name' => 'Refrigerator',
            ],
            [
                'id' => 99,
                'sync_id' => 99,
                'locale' => 'en',
                'translation_id' => 99,
                'name' => 'Tea/Coffee maker',
            ],
            [
                'id' => 100,
                'sync_id' => 100,
                'locale' => 'en',
                'translation_id' => 100,
                'name' => 'Coffee machine',
            ],
            [
                'id' => 101,
                'sync_id' => 101,
                'locale' => 'en',
                'translation_id' => 101,
                'name' => 'High chair',
            ],
            [
                'id' => 102,
                'sync_id' => 102,
                'locale' => 'en',
                'translation_id' => 102,
                'name' => 'Key Card Access',
            ],
            [
                'id' => 103,
                'sync_id' => 103,
                'locale' => 'en',
                'translation_id' => 103,
                'name' => 'Smoke Alarm',
            ],
            [
                'id' => 104,
                'sync_id' => 104,
                'locale' => 'en',
                'translation_id' => 104,
                'name' => 'Fire Extinguisher',
            ],
            [
                'id' => 105,
                'sync_id' => 105,
                'locale' => 'en',
                'translation_id' => 105,
                'name' => 'Lockers',
            ],
            [
                'id' => 106,
                'sync_id' => 106,
                'locale' => 'en',
                'translation_id' => 106,
                'name' => 'Key Access',
            ],
            [
                'id' => 107,
                'sync_id' => 107,
                'locale' => 'en',
                'translation_id' => 107,
                'name' => 'Executive Lounge Access',
            ],
            [
                'id' => 108,
                'sync_id' => 108,
                'locale' => 'en',
                'translation_id' => 108,
                'name' => 'Alarm clock',
            ],
            [
                'id' => 109,
                'sync_id' => 109,
                'locale' => 'en',
                'translation_id' => 109,
                'name' => 'Wake-up service',
            ],
            [
                'id' => 110,
                'sync_id' => 110,
                'locale' => 'en',
                'translation_id' => 110,
                'name' => 'Wake up service/Alarm clock',
            ],
            [
                'id' => 111,
                'sync_id' => 111,
                'locale' => 'en',
                'translation_id' => 111,
                'name' => 'Linens',
            ],
            [
                'id' => 112,
                'sync_id' => 112,
                'locale' => 'en',
                'translation_id' => 112,
                'name' => 'Towels',
            ],
            [
                'id' => 113,
                'sync_id' => 113,
                'locale' => 'en',
                'translation_id' => 113,
                'name' => 'Patio',
            ],
            [
                'id' => 114,
                'sync_id' => 114,
                'locale' => 'en',
                'translation_id' => 114,
                'name' => 'City view',
            ],
            [
                'id' => 115,
                'sync_id' => 115,
                'locale' => 'en',
                'translation_id' => 115,
                'name' => 'Garden view',
            ],
            [
                'id' => 116,
                'sync_id' => 116,
                'locale' => 'en',
                'translation_id' => 116,
                'name' => 'Lake view',
            ],
            [
                'id' => 117,
                'sync_id' => 117,
                'locale' => 'en',
                'translation_id' => 117,
                'name' => 'Landmark view',
            ],
            [
                'id' => 118,
                'sync_id' => 118,
                'locale' => 'en',
                'translation_id' => 118,
                'name' => 'Mountain view',
            ],
            [
                'id' => 119,
                'sync_id' => 119,
                'locale' => 'en',
                'translation_id' => 119,
                'name' => 'River view',
            ],
            // [
            //     'id' => ,
            //     'sync_id' => ,
            //     'locale' => 'en',
            //     'translation_id' => ,
            //     'name' => '',
            // ],
        ]);
    }
}
