<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class FacilitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('facilities')->insert([
            [
                'id' => 1,
                'sync_id' => 1,
                'facility_category_id' => 1,
                'name' => 'Далайн эрэг',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 2,
                'sync_id' => 2,
                'facility_category_id' => 1,
                'name' => 'Бассейн, усан сан',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 3,
                'sync_id' => 3,
                'facility_category_id' => 1,
                'name' => 'Спа, рашаан сувилал',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 4,
                'sync_id' => 4,
                'facility_category_id' => 1,
                'name' => 'Гэр бүлийн өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 5,
                'sync_id' => 5,
                'facility_category_id' => 1,
                'name' => 'Агааржуулалт',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 6,
                'sync_id' => 6,
                'facility_category_id' => 1,
                'name' => 'Тамхи татаж болох өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 7,
                'sync_id' => 7,
                'facility_category_id' => 1,
                'name' => 'Тамхи татаж болохгүй өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 8,
                'sync_id' => 8,
                'facility_category_id' => 1,
                'name' => 'Ресторан',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 9,
                'sync_id' => 9,
                'facility_category_id' => 1,
                'name' => 'Саун',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 10,
                'sync_id' => 10,
                'facility_category_id' => 1,
                'name' => 'Онгоцны буудлаас тосож авах',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 11,
                'sync_id' => 11,
                'facility_category_id' => 1,
                'name' => '24 цагын хүлээн авах хэсэг',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 12,
                'sync_id' => 12,
                'facility_category_id' => 1,
                'name' => 'Фитнесс төв',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 13,
                'sync_id' => 13,
                'facility_category_id' => 1,
                'name' => 'Халуун усны онгоц',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 14,
                'sync_id' => 14,
                'facility_category_id' => 1,
                'name' => 'Өрөөний үйлчилгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 15,
                'sync_id' => 15,
                'facility_category_id' => 1,
                'name' => 'Тагт',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 16,
                'sync_id' => 16,
                'facility_category_id' => 1,
                'name' => 'Бар',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 17,
                'sync_id' => 17,
                'facility_category_id' => 1,
                'name' => 'Цэцэрлэг',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 18,
                'sync_id' => 18,
                'facility_category_id' => 1,
                'name' => 'Хүүхдийн өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 19,
                'sync_id' => 19,
                'facility_category_id' => 2,
                'name' => 'Теннисний тоног төхөөрөмж',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 20,
                'sync_id' => 20,
                'facility_category_id' => 2,
                'name' => 'Бадминтон тоног төхөөрөмж',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 21,
                'sync_id' => 21,
                'facility_category_id' => 2,
                'name' => 'Явган аялал хийх',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 22,
                'sync_id' => 22,
                'facility_category_id' => 2,
                'name' => 'Дугуйгаар аялах',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 23,
                'sync_id' => 23,
                'facility_category_id' => 2,
                'name' => 'Орон нутгийн соёлтой танилцах аялал',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 24,
                'sync_id' => 24,
                'facility_category_id' => 2,
                'name' => 'Амьд хөгжим / Тоглолт',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 25,
                'sync_id' => 25,
                'facility_category_id' => 2,
                'name' => 'Шууд спортын арга хэмжээнүүд (шууд нэвтрүүлэг)',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 26,
                'sync_id' => 26,
                'facility_category_id' => 2,
                'name' => 'Байт харваа, нум сум',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 27,
                'sync_id' => 27,
                'facility_category_id' => 2,
                'name' => 'Газрын теннисний талбай',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 28,
                'sync_id' => 28,
                'facility_category_id' => 2,
                'name' => 'Биллиардны ширээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 29,
                'sync_id' => 29,
                'facility_category_id' => 2,
                'name' => 'Ширээний теннис',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 30,
                'sync_id' => 30,
                'facility_category_id' => 2,
                'name' => 'Дартс',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 31,
                'sync_id' => 31,
                'facility_category_id' => 2,
                'name' => 'Усан спортын байгууламжууд',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 32,
                'sync_id' => 32,
                'facility_category_id' => 2,
                'name' => 'Загас барих',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 33,
                'sync_id' => 33,
                'facility_category_id' => 2,
                'name' => 'Морь унах',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 34,
                'sync_id' => 34,
                'facility_category_id' => 2,
                'name' => 'Дугуй унах ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 35,
                'sync_id' => 35,
                'facility_category_id' => 2,
                'name' => 'Уулын аялал / алхалт',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 36,
                'sync_id' => 36,
                'facility_category_id' => 2,
                'name' => 'Цанаар гулгах',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 37,
                'sync_id' => 37,
                'facility_category_id' => 3,
                'name' => 'Хүүхдийн хоол / хүүхдийн багц',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 38,
                'sync_id' => 38,
                'facility_category_id' => 3,
                'name' => 'Хүүхдэд ээлтэй буфет',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 39,
                'sync_id' => 39,
                'facility_category_id' => 3,
                'name' => 'Дарс / оргилуун дарс',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 40,
                'sync_id' => 40,
                'facility_category_id' => 3,
                'name' => 'Савтай ус',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 41,
                'sync_id' => 41,
                'facility_category_id' => 3,
                'name' => 'Жимс',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 42,
                'sync_id' => 42,
                'facility_category_id' => 3,
                'name' => 'Шоколад / жигнэмэг',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 43,
                'sync_id' => 43,
                'facility_category_id' => 3,
                'name' => 'Кофе шоп',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 44,
                'sync_id' => 44,
                'facility_category_id' => 3,
                'name' => 'Зуушны баар',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 45,
                'sync_id' => 45,
                'facility_category_id' => 3,
                'name' => 'Савласан үдийн хоол',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 46,
                'sync_id' => 46,
                'facility_category_id' => 3,
                'name' => 'BBQ байгууламжууд',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 47,
                'sync_id' => 47,
                'facility_category_id' => 3,
                'name' => 'Тусгай дэглэмний хоол (хүсэлтээр)',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 48,
                'sync_id' => 48,
                'facility_category_id' => 3,
                'name' => 'Өрөөнд өглөөний цай',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 49,
                'sync_id' => 49,
                'facility_category_id' => 4,
                'name' => 'Усан гулсуур',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 50,
                'sync_id' => 50,
                'facility_category_id' => 4,
                'name' => 'Усан бассейны наран шарлагын алчуур',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 51,
                'sync_id' => 51,
                'facility_category_id' => 4,
                'name' => 'Далайн эрэг / унтлагын сандал',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 52,
                'sync_id' => 52,
                'facility_category_id' => 4,
                'name' => 'Далайн эрэг дээрх шүхэр',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 53,
                'sync_id' => 53,
                'facility_category_id' => 4,
                'name' => 'Гоо сайхны үйлчилгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 54,
                'sync_id' => 54,
                'facility_category_id' => 4,
                'name' => 'Спа байгууламжууд',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 55,
                'sync_id' => 55,
                'facility_category_id' => 4,
                'name' => 'Уурын өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 56,
                'sync_id' => 56,
                'facility_category_id' => 4,
                'name' => 'Амралтын өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 57,
                'sync_id' => 57,
                'facility_category_id' => 4,
                'name' => 'Хөлийн банн',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 58,
                'sync_id' => 58,
                'facility_category_id' => 4,
                'name' => 'Спа / эрүүл мэндийн багц',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 59,
                'sync_id' => 59,
                'facility_category_id' => 4,
                'name' => 'Массажны сандал',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 60,
                'sync_id' => 60,
                'facility_category_id' => 4,
                'name' => 'Фитнесс төв',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 61,
                'sync_id' => 61,
                'facility_category_id' => 4,
                'name' => 'Хувцасны шүүгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 62,
                'sync_id' => 62,
                'facility_category_id' => 4,
                'name' => 'Хүүхдийн усан сан',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 63,
                'sync_id' => 63,
                'facility_category_id' => 4,
                'name' => 'Hot spring bath',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 64,
                'sync_id' => 64,
                'facility_category_id' => 4,
                'name' => 'Массаж',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 65,
                'sync_id' => 65,
                'facility_category_id' => 4,
                'name' => 'Open-air bath',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 66,
                'sync_id' => 66,
                'facility_category_id' => 4,
                'name' => 'Bathhouse',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 67,
                'sync_id' => 67,
                'facility_category_id' => 5,
                'name' => 'Харуул хамгаалалтай зогсоол',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 68,
                'sync_id' => 68,
                'facility_category_id' => 5,
                'name' => 'Ил зогсоол',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 69,
                'sync_id' => 69,
                'facility_category_id' => 5,
                'name' => 'Машины граж',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 70,
                'sync_id' => 70,
                'facility_category_id' => 5,
                'name' => 'Хөгжилийн бэрхшээлтэй хүний зогсоол',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 71,
                'sync_id' => 71,
                'facility_category_id' => 5,
                'name' => 'Тосох хүргэж өгөх үйлчилгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 72,
                'sync_id' => 72,
                'facility_category_id' => 5,
                'name' => 'Bikes available (free)',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 73,
                'sync_id' => 73,
                'facility_category_id' => 5,
                'name' => 'Унадаг дугуй түрээслэх (нэмэлт төлбөр)',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 74,
                'sync_id' => 74,
                'facility_category_id' => 5,
                'name' => 'Машин түрээслэх',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 76,
                'sync_id' => 76,
                'facility_category_id' => 6,
                'name' => 'Үзэсгэлэн / аялал жуулчлалын тасалбар',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 77,
                'sync_id' => 77,
                'facility_category_id' => 6,
                'name' => 'Private check-in/out',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 78,
                'sync_id' => 78,
                'facility_category_id' => 6,
                'name' => 'Express check-in/out',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 79,
                'sync_id' => 79,
                'facility_category_id' => 6,
                'name' => 'Зочин д туслах ажилтан',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 80,
                'sync_id' => 80,
                'facility_category_id' => 6,
                'name' => 'Tour desk',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 81,
                'sync_id' => 81,
                'facility_category_id' => 6,
                'name' => 'Валютын солих',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 82,
                'sync_id' => 82,
                'facility_category_id' => 6,
                'name' => 'АТМ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 83,
                'sync_id' => 83,
                'facility_category_id' => 6,
                'name' => 'Сэйф',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 84,
                'sync_id' => 84,
                'facility_category_id' => 6,
                'name' => 'Сонин',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 85,
                'sync_id' => 85,
                'facility_category_id' => 7,
                'name' => 'Гаднах орчин тохижуулсан',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 86,
                'sync_id' => 86,
                'facility_category_id' => 7,
                'name' => 'Гадна орчинд хооллох орчинтой',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 87,
                'sync_id' => 87,
                'facility_category_id' => 7,
                'name' => 'Гадаа ил зуух',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 88,
                'sync_id' => 88,
                'facility_category_id' => 7,
                'name' => 'Sun deck',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 89,
                'sync_id' => 89,
                'facility_category_id' => 7,
                'name' => 'Дундын гал тогоо',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 90,
                'sync_id' => 90,
                'facility_category_id' => 7,
                'name' => 'Нийтийн амралтын өрөө / ТВ үзэх өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 91,
                'sync_id' => 91,
                'facility_category_id' => 7,
                'name' => 'Тоглоомын өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 92,
                'sync_id' => 92,
                'facility_category_id' => 7,
                'name' => 'Номын сан',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 93,
                'sync_id' => 93,
                'facility_category_id' => 8,
                'name' => 'Хүүхдэд зориулсан ном, DVD ба хөгжим',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 94,
                'sync_id' => 94,
                'facility_category_id' => 8,
                'name' => 'Дотор тоглоомын талбай',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 95,
                'sync_id' => 95,
                'facility_category_id' => 8,
                'name' => 'Хүүхдэд зориулсан гаднах тоглоомын талбай',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 96,
                'sync_id' => 96,
                'facility_category_id' => 8,
                'name' => 'Оройн үйл ажиллагаа',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 97,
                'sync_id' => 97,
                'facility_category_id' => 8,
                'name' => 'Бүжгийн талбай / DJ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 98,
                'sync_id' => 98,
                'facility_category_id' => 8,
                'name' => 'Караоке',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 99,
                'sync_id' => 99,
                'facility_category_id' => 8,
                'name' => 'Тоглоомын талбай',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 100,
                'sync_id' => 100,
                'facility_category_id' => 8,
                'name' => 'Нялх хүүхэд асрах / хүүхэд харах үйлчилгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 101,
                'sync_id' => 101,
                'facility_category_id' => 9,
                'name' => 'Хуурай цэвэрлэгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 102,
                'sync_id' => 102,
                'facility_category_id' => 9,
                'name' => 'Хувцас индүүдэх үйлчилгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 103,
                'sync_id' => 103,
                'facility_category_id' => 9,
                'name' => 'Хувцас угаалгын газар / үйлчилгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 104,
                'sync_id' => 104,
                'facility_category_id' => 9,
                'name' => 'Өдөр тутам өрөө цэвэрлэгээний үйлчилгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 105,
                'sync_id' => 105,
                'facility_category_id' => 9,
                'name' => 'Гутал цэвэрлэх үйлчилгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 106,
                'sync_id' => 106,
                'facility_category_id' => 9,
                'name' => 'Хослол хадгалах индүүдэх',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 107,
                'sync_id' => 107,
                'facility_category_id' => 10,
                'name' => 'Уулзалт / хүлээн авалтын танхим',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 108,
                'sync_id' => 108,
                'facility_category_id' => 10,
                'name' => 'Бизнес төв',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 109,
                'sync_id' => 109,
                'facility_category_id' => 10,
                'name' => 'Факс / хуулбарын өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 110,
                'sync_id' => 110,
                'facility_category_id' => 11,
                'name' => 'Буудлын дэлгүүр',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 111,
                'sync_id' => 111,
                'facility_category_id' => 11,
                'name' => 'КОНВЕНИЕНС Дэлгүүр',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 112,
                'sync_id' => 112,
                'facility_category_id' => 11,
                'name' => 'Үс / гоо сайхны салон',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 113,
                'sync_id' => 113,
                'facility_category_id' => 11,
                'name' => 'Бэлэг дурсгалын дэлгүүр',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 114,
                'sync_id' => 114,
                'facility_category_id' => 12,
                'name' => '24-hour security',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 115,
                'sync_id' => 115,
                'facility_category_id' => 12,
                'name' => 'Түлхүүр нэвтрэх',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 116,
                'sync_id' => 116,
                'facility_category_id' => 12,
                'name' => 'Картын түлхүүрээр нэвтрэх',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 117,
                'sync_id' => 117,
                'facility_category_id' => 12,
                'name' => 'Аюулгүй байдлын дохиолол',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 118,
                'sync_id' => 118,
                'facility_category_id' => 12,
                'name' => 'Галын дохиолол',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 119,
                'sync_id' => 119,
                'facility_category_id' => 12,
                'name' => 'Олон нийтийн бүсэд CCTV-тэй',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 120,
                'sync_id' => 120,
                'facility_category_id' => 12,
                'name' => 'Байгууламжийн гадна CCTV-тэй',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 121,
                'sync_id' => 121,
                'facility_category_id' => 12,
                'name' => 'Гал унтраагч',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 122,
                'sync_id' => 122,
                'facility_category_id' => 12,
                'name' => 'Зөвхөн насанд хүрэгчдийнх',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 123,
                'sync_id' => 123,
                'facility_category_id' => 12,
                'name' => 'Гипоаллергенийн өрөө авах боломжтой',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 124,
                'sync_id' => 124,
                'facility_category_id' => 12,
                'name' => 'Тамхигүй орчин',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 125,
                'sync_id' => 125,
                'facility_category_id' => 12,
                'name' => 'Тамхи татах зориулалтын талбай',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 126,
                'sync_id' => 126,
                'facility_category_id' => 12,
                'name' => 'Хөгжлийн бэрхшээлтэй зочдод зориулсан үйлчилгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 127,
                'sync_id' => 127,
                'facility_category_id' => 12,
                'name' => 'Цахилгаан шат',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 128,
                'sync_id' => 128,
                'facility_category_id' => 12,
                'name' => 'Дуу тусгаарлагчтай өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 129,
                'sync_id' => 129,
                'facility_category_id' => 12,
                'name' => 'Бал сарын өрөө',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 130,
                'sync_id' => 130,
                'facility_category_id' => 12,
                'name' => 'VIP танхим',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 131,
                'sync_id' => 131,
                'facility_category_id' => 12,
                'name' => 'Халаалт',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 132,
                'sync_id' => 132,
                'facility_category_id' => 12,
                'name' => 'Шүүгээ',
                'is_default' => 0,
                'is_most' => 0,
            ],
            [
                'id' => 133,
                'sync_id' => 133,
                'facility_category_id' => 12,
                'name' => 'Тээш хадгалах',
                'is_default' => 0,
                'is_most' => 0,
            ],
        ]);

        DB::table('facility_translations')->insert([
            [
                'id' => 1,
                'sync_id' => 1,
                'locale' => 'en',
                'translation_id' => 1,
                'name' => 'Beach',
            ],
            [
                'id' => 2,
                'sync_id' => 2,
                'locale' => 'en',
                'translation_id' => 2,
                'name' => 'Swimming pool',
            ],
            [
                'id' => 3,
                'sync_id' => 3,
                'locale' => 'en',
                'translation_id' => 3,
                'name' => 'Spa',
            ],
            [
                'id' => 4,
                'sync_id' => 4,
                'locale' => 'en',
                'translation_id' => 4,
                'name' => 'Family rooms',
            ],
            [
                'id' => 5,
                'sync_id' => 5,
                'locale' => 'en',
                'translation_id' => 5,
                'name' => 'Air conditioning',
            ],
            [
                'id' => 6,
                'sync_id' => 6,
                'locale' => 'en',
                'translation_id' => 6,
                'name' => 'Smoking room',
            ],
            [
                'id' => 7,
                'sync_id' => 7,
                'locale' => 'en',
                'translation_id' => 7,
                'name' => 'Non-smoking rooms',
            ],
            [
                'id' => 8,
                'sync_id' => 8,
                'locale' => 'en',
                'translation_id' => 8,
                'name' => 'Restaurant',
            ],
            [
                'id' => 9,
                'sync_id' => 9,
                'locale' => 'en',
                'translation_id' => 9,
                'name' => 'Sauna',
            ],
            [
                'id' => 10,
                'sync_id' => 10,
                'locale' => 'en',
                'translation_id' => 10,
                'name' => 'Airport shuttle',
            ],
            [
                'id' => 11,
                'sync_id' => 11,
                'locale' => 'en',
                'translation_id' => 11,
                'name' => '24-hour front desk',
            ],
            [
                'id' => 12,
                'sync_id' => 12,
                'locale' => 'en',
                'translation_id' => 12,
                'name' => 'Fitness center',
            ],
            [
                'id' => 13,
                'sync_id' => 13,
                'locale' => 'en',
                'translation_id' => 13,
                'name' => 'Hot tub/Jacuzzi',
            ],
            [
                'id' => 14,
                'sync_id' => 14,
                'locale' => 'en',
                'translation_id' => 14,
                'name' => 'Room service',
            ],
            [
                'id' => 15,
                'sync_id' => 15,
                'locale' => 'en',
                'translation_id' => 15,
                'name' => 'Terrace',
            ],
            [
                'id' => 16,
                'sync_id' => 16,
                'locale' => 'en',
                'translation_id' => 16,
                'name' => 'Bar',
            ],
            [
                'id' => 17,
                'sync_id' => 17,
                'locale' => 'en',
                'translation_id' => 17,
                'name' => 'Garden',
            ],
            [
                'id' => 18,
                'sync_id' => 18,
                'locale' => 'en',
                'translation_id' => 18,
                'name' => "Kid's room",
            ],
            [
                'id' => 19,
                'sync_id' => 19,
                'locale' => 'en',
                'translation_id' => 19,
                'name' => 'Tennis equipment',
            ],
            [
                'id' => 20,
                'sync_id' => 20,
                'locale' => 'en',
                'translation_id' => 20,
                'name' => 'Badminton equipment',
            ],
            [
                'id' => 21,
                'sync_id' => 21,
                'locale' => 'en',
                'translation_id' => 21,
                'name' => 'Walking tours',
            ],
            [
                'id' => 22,
                'sync_id' => 22,
                'locale' => 'en',
                'translation_id' => 22,
                'name' => 'Bike tours',
            ],
            [
                'id' => 23,
                'sync_id' => 23,
                'locale' => 'en',
                'translation_id' => 23,
                'name' => 'Tour or class about local culture',
            ],
            [
                'id' => 24,
                'sync_id' => 24,
                'locale' => 'en',
                'translation_id' => 24,
                'name' => 'Live music/Performance',
            ],
            [
                'id' => 25,
                'sync_id' => 25,
                'locale' => 'en',
                'translation_id' => 25,
                'name' => 'Live sports events (broadcast)',
            ],
            [
                'id' => 26,
                'sync_id' => 26,
                'locale' => 'en',
                'translation_id' => 26,
                'name' => 'Archery',
            ],
            [
                'id' => 27,
                'sync_id' => 27,
                'locale' => 'en',
                'translation_id' => 27,
                'name' => 'Tennis court',
            ],
            [
                'id' => 28,
                'sync_id' => 28,
                'locale' => 'en',
                'translation_id' => 28,
                'name' => 'Pool table',
            ],
            [
                'id' => 29,
                'sync_id' => 29,
                'locale' => 'en',
                'translation_id' => 29,
                'name' => 'Ping-pong',
            ],
            [
                'id' => 30,
                'sync_id' => 30,
                'locale' => 'en',
                'translation_id' => 30,
                'name' => 'Darts',
            ],
            [
                'id' => 31,
                'sync_id' => 31,
                'locale' => 'en',
                'translation_id' => 31,
                'name' => 'Water sports facilities (on site)',
            ],
            [
                'id' => 32,
                'sync_id' => 32,
                'locale' => 'en',
                'translation_id' => 32,
                'name' => 'Fishing',
            ],
            [
                'id' => 33,
                'sync_id' => 33,
                'locale' => 'en',
                'translation_id' => 33,
                'name' => 'Horseback riding',
            ],
            [
                'id' => 34,
                'sync_id' => 34,
                'locale' => 'en',
                'translation_id' => 34,
                'name' => 'Cycling',
            ],
            [
                'id' => 35,
                'sync_id' => 35,
                'locale' => 'en',
                'translation_id' => 35,
                'name' => 'Hiking',
            ],
            [
                'id' => 36,
                'sync_id' => 36,
                'locale' => 'en',
                'translation_id' => 36,
                'name' => "Skiing",
            ],
            [
                'id' => 37,
                'sync_id' => 37,
                'locale' => 'en',
                'translation_id' => 37,
                'name' => "Kids' meals",
            ],
            [
                'id' => 38,
                'sync_id' => 38,
                'locale' => 'en',
                'translation_id' => 38,
                'name' => 'Kid-friendly buffet',
            ],
            [
                'id' => 39,
                'sync_id' => 39,
                'locale' => 'en',
                'translation_id' => 39,
                'name' => 'Wine/Champagne',
            ],
            [
                'id' => 40,
                'sync_id' => 40,
                'locale' => 'en',
                'translation_id' => 40,
                'name' => 'Bottle of water',
            ],
            [
                'id' => 41,
                'sync_id' => 41,
                'locale' => 'en',
                'translation_id' => 41,
                'name' => 'Fruit',
            ],
            [
                'id' => 42,
                'sync_id' => 42,
                'locale' => 'en',
                'translation_id' => 42,
                'name' => 'Chocolate/Cookies',
            ],
            [
                'id' => 43,
                'sync_id' => 43,
                'locale' => 'en',
                'translation_id' => 43,
                'name' => 'On-site coffee shop',
            ],
            [
                'id' => 44,
                'sync_id' => 44,
                'locale' => 'en',
                'translation_id' => 44,
                'name' => 'Snack bar',
            ],
            [
                'id' => 45,
                'sync_id' => 45,
                'locale' => 'en',
                'translation_id' => 45,
                'name' => 'Packed lunches',
            ],
            [
                'id' => 46,
                'sync_id' => 46,
                'locale' => 'en',
                'translation_id' => 46,
                'name' => 'BBQ facilities',
            ],
            [
                'id' => 47,
                'sync_id' => 47,
                'locale' => 'en',
                'translation_id' => 47,
                'name' => 'Special diet meals (on request)',
            ],
            [
                'id' => 48,
                'sync_id' => 48,
                'locale' => 'en',
                'translation_id' => 48,
                'name' => 'Breakfast in the room',
            ],
            [
                'id' => 49,
                'sync_id' => 49,
                'locale' => 'en',
                'translation_id' => 49,
                'name' => "Waterslide",
            ],
            [
                'id' => 50,
                'sync_id' => 50,
                'locale' => 'en',
                'translation_id' => 50,
                'name' => 'Pool/Beach towels',
            ],
            [
                'id' => 51,
                'sync_id' => 51,
                'locale' => 'en',
                'translation_id' => 51,
                'name' => 'Beach chairs/Loungers',
            ],
            [
                'id' => 52,
                'sync_id' => 52,
                'locale' => 'en',
                'translation_id' => 52,
                'name' => 'Beach umbrellas',
            ],
            [
                'id' => 53,
                'sync_id' => 53,
                'locale' => 'en',
                'translation_id' => 53,
                'name' => 'Beauty services',
            ],
            [
                'id' => 54,
                'sync_id' => 54,
                'locale' => 'en',
                'translation_id' => 54,
                'name' => 'Spa facilities',
            ],
            [
                'id' => 55,
                'sync_id' => 55,
                'locale' => 'en',
                'translation_id' => 55,
                'name' => 'Steam room',
            ],
            [
                'id' => 56,
                'sync_id' => 56,
                'locale' => 'en',
                'translation_id' => 56,
                'name' => 'Spa lounge/Relaxation area',
            ],
            [
                'id' => 57,
                'sync_id' => 57,
                'locale' => 'en',
                'translation_id' => 57,
                'name' => 'Foot bath',
            ],
            [
                'id' => 58,
                'sync_id' => 58,
                'locale' => 'en',
                'translation_id' => 58,
                'name' => 'Spa/Wellness packages',
            ],
            [
                'id' => 59,
                'sync_id' => 59,
                'locale' => 'en',
                'translation_id' => 59,
                'name' => 'Massage chair',
            ],
            [
                'id' => 60,
                'sync_id' => 60,
                'locale' => 'en',
                'translation_id' => 60,
                'name' => 'Fitness',
            ],
            [
                'id' => 61,
                'sync_id' => 61,
                'locale' => 'en',
                'translation_id' => 61,
                'name' => 'Locker rooms',
            ],
            [
                'id' => 62,
                'sync_id' => 62,
                'locale' => 'en',
                'translation_id' => 62,
                'name' => "Kids' pool",
            ],
            [
                'id' => 63,
                'sync_id' => 63,
                'locale' => 'en',
                'translation_id' => 63,
                'name' => 'Hot spring bath',
            ],
            [
                'id' => 64,
                'sync_id' => 64,
                'locale' => 'en',
                'translation_id' => 64,
                'name' => 'Massage',
            ],
            [
                'id' => 65,
                'sync_id' => 65,
                'locale' => 'en',
                'translation_id' => 65,
                'name' => 'Open-air bath',
            ],
            [
                'id' => 66,
                'sync_id' => 66,
                'locale' => 'en',
                'translation_id' => 66,
                'name' => 'Bathhouse',
            ],
            [
                'id' => 67,
                'sync_id' => 67,
                'locale' => 'en',
                'translation_id' => 67,
                'name' => "Secure parking",
            ],
            [
                'id' => 68,
                'sync_id' => 68,
                'locale' => 'en',
                'translation_id' => 68,
                'name' => 'Street parking',
            ],
            [
                'id' => 69,
                'sync_id' => 69,
                'locale' => 'en',
                'translation_id' => 69,
                'name' => 'Parking garage',
            ],
            [
                'id' => 70,
                'sync_id' => 70,
                'locale' => 'en',
                'translation_id' => 70,
                'name' => 'Accessible parking',
            ],
            [
                'id' => 71,
                'sync_id' => 71,
                'locale' => 'en',
                'translation_id' => 71,
                'name' => 'Shuttle service',
            ],
            [
                'id' => 72,
                'sync_id' => 72,
                'locale' => 'en',
                'translation_id' => 72,
                'name' => 'Bikes available (free)',
            ],
            [
                'id' => 73,
                'sync_id' => 73,
                'locale' => 'en',
                'translation_id' => 73,
                'name' => 'Bicycle rental (additional charge)',
            ],
            [
                'id' => 74,
                'sync_id' => 74,
                'locale' => 'en',
                'translation_id' => 74,
                'name' => 'Car rental',
            ],
            [
                'id' => 76,
                'sync_id' => 76,
                'locale' => 'en',
                'translation_id' => 76,
                'name' => "Tickets to shows/attractions",
            ],
            [
                'id' => 77,
                'sync_id' => 77,
                'locale' => 'en',
                'translation_id' => 77,
                'name' => 'Private check-in/out',
            ],
            [
                'id' => 78,
                'sync_id' => 78,
                'locale' => 'en',
                'translation_id' => 78,
                'name' => 'Express check-in/out',
            ],
            [
                'id' => 79,
                'sync_id' => 79,
                'locale' => 'en',
                'translation_id' => 79,
                'name' => 'Concierge',
            ],
            [
                'id' => 80,
                'sync_id' => 80,
                'locale' => 'en',
                'translation_id' => 80,
                'name' => 'Tour desk',
            ],
            [
                'id' => 81,
                'sync_id' => 81,
                'locale' => 'en',
                'translation_id' => 81,
                'name' => 'Currency exchange',
            ],
            [
                'id' => 82,
                'sync_id' => 82,
                'locale' => 'en',
                'translation_id' => 82,
                'name' => 'ATM on site',
            ],
            [
                'id' => 83,
                'sync_id' => 83,
                'locale' => 'en',
                'translation_id' => 83,
                'name' => 'Safe',
            ],
            [
                'id' => 84,
                'sync_id' => 84,
                'locale' => 'en',
                'translation_id' => 84,
                'name' => 'Newspapers',
            ],
            [
                'id' => 85,
                'sync_id' => 85,
                'locale' => 'en',
                'translation_id' => 85,
                'name' => "Outdoor furniture",
            ],
            [
                'id' => 86,
                'sync_id' => 86,
                'locale' => 'en',
                'translation_id' => 86,
                'name' => 'Picnic area',
            ],
            [
                'id' => 87,
                'sync_id' => 87,
                'locale' => 'en',
                'translation_id' => 87,
                'name' => 'Outdoor fireplace',
            ],
            [
                'id' => 88,
                'sync_id' => 88,
                'locale' => 'en',
                'translation_id' => 88,
                'name' => 'Sun deck',
            ],
            [
                'id' => 89,
                'sync_id' => 89,
                'locale' => 'en',
                'translation_id' => 89,
                'name' => 'Shared kitchen',
            ],
            [
                'id' => 90,
                'sync_id' => 90,
                'locale' => 'en',
                'translation_id' => 90,
                'name' => 'Shared lounge/TV area',
            ],
            [
                'id' => 91,
                'sync_id' => 91,
                'locale' => 'en',
                'translation_id' => 91,
                'name' => 'Game room',
            ],
            [
                'id' => 92,
                'sync_id' => 92,
                'locale' => 'en',
                'translation_id' => 92,
                'name' => 'Library',
            ],
            [
                'id' => 93,
                'sync_id' => 93,
                'locale' => 'en',
                'translation_id' => 93,
                'name' => "Books, DVDs & music for kids",
            ],
            [
                'id' => 94,
                'sync_id' => 94,
                'locale' => 'en',
                'translation_id' => 94,
                'name' => 'Indoor play area',
            ],
            [
                'id' => 95,
                'sync_id' => 95,
                'locale' => 'en',
                'translation_id' => 95,
                'name' => 'Outdoor play equipment for kids',
            ],
            [
                'id' => 96,
                'sync_id' => 96,
                'locale' => 'en',
                'translation_id' => 96,
                'name' => 'Evening entertainment',
            ],
            [
                'id' => 97,
                'sync_id' => 97,
                'locale' => 'en',
                'translation_id' => 97,
                'name' => 'Nightclub/DJ',
            ],
            [
                'id' => 98,
                'sync_id' => 98,
                'locale' => 'en',
                'translation_id' => 98,
                'name' => 'Karaoke',
            ],
            [
                'id' => 99,
                'sync_id' => 99,
                'locale' => 'en',
                'translation_id' => 99,
                'name' => 'Playground',
            ],
            [
                'id' => 100,
                'sync_id' => 100,
                'locale' => 'en',
                'translation_id' => 100,
                'name' => 'Babysitting/Child services',
            ],
            [
                'id' => 101,
                'sync_id' => 101,
                'locale' => 'en',
                'translation_id' => 101,
                'name' => "Dry cleaning",
            ],
            [
                'id' => 102,
                'sync_id' => 102,
                'locale' => 'en',
                'translation_id' => 102,
                'name' => 'Ironing service',
            ],
            [
                'id' => 103,
                'sync_id' => 103,
                'locale' => 'en',
                'translation_id' => 103,
                'name' => 'Laundry',
            ],
            [
                'id' => 104,
                'sync_id' => 104,
                'locale' => 'en',
                'translation_id' => 104,
                'name' => 'Daily housekeeping',
            ],
            [
                'id' => 105,
                'sync_id' => 105,
                'locale' => 'en',
                'translation_id' => 105,
                'name' => 'Shoeshine',
            ],
            [
                'id' => 106,
                'sync_id' => 106,
                'locale' => 'en',
                'translation_id' => 106,
                'name' => 'Suit press',
            ],
            [
                'id' => 107,
                'sync_id' => 107,
                'locale' => 'en',
                'translation_id' => 107,
                'name' => "Meeting/Banquet facilities",
            ],
            [
                'id' => 108,
                'sync_id' => 108,
                'locale' => 'en',
                'translation_id' => 108,
                'name' => 'Business centere',
            ],
            [
                'id' => 109,
                'sync_id' => 109,
                'locale' => 'en',
                'translation_id' => 109,
                'name' => 'Fax/Photocopying',
            ],
            [
                'id' => 110,
                'sync_id' => 110,
                'locale' => 'en',
                'translation_id' => 110,
                'name' => "Shops (on site)",
            ],
            [
                'id' => 111,
                'sync_id' => 111,
                'locale' => 'en',
                'translation_id' => 111,
                'name' => 'Convenience store (on site)',
            ],
            [
                'id' => 112,
                'sync_id' => 112,
                'locale' => 'en',
                'translation_id' => 112,
                'name' => 'Hair/Beauty salon',
            ],
            [
                'id' => 113,
                'sync_id' => 113,
                'locale' => 'en',
                'translation_id' => 113,
                'name' => 'Gift shop',
            ],
            [
                'id' => 114,
                'sync_id' => 114,
                'locale' => 'en',
                'translation_id' => 114,
                'name' => "24-hour security",
            ],
            [
                'id' => 115,
                'sync_id' => 115,
                'locale' => 'en',
                'translation_id' => 115,
                'name' => 'Key access',
            ],
            [
                'id' => 116,
                'sync_id' => 116,
                'locale' => 'en',
                'translation_id' => 116,
                'name' => 'Key card access',
            ],
            [
                'id' => 117,
                'sync_id' => 117,
                'locale' => 'en',
                'translation_id' => 117,
                'name' => 'Security alarm',
            ],
            [
                'id' => 118,
                'sync_id' => 118,
                'locale' => 'en',
                'translation_id' => 118,
                'name' => 'Smoke alarms',
            ],
            [
                'id' => 119,
                'sync_id' => 119,
                'locale' => 'en',
                'translation_id' => 119,
                'name' => 'CCTV in common areas',
            ],
            [
                'id' => 120,
                'sync_id' => 120,
                'locale' => 'en',
                'translation_id' => 120,
                'name' => 'CCTV outside property',
            ],
            [
                'id' => 121,
                'sync_id' => 121,
                'locale' => 'en',
                'translation_id' => 121,
                'name' => 'Fire extinguishers',
            ],
            [
                'id' => 122,
                'sync_id' => 122,
                'locale' => 'en',
                'translation_id' => 122,
                'name' => 'Adults only',
            ],
            [
                'id' => 123,
                'sync_id' => 123,
                'locale' => 'en',
                'translation_id' => 123,
                'name' => 'Hypoallergenic Room Available',
            ],
            [
                'id' => 124,
                'sync_id' => 124,
                'locale' => 'en',
                'translation_id' => 124,
                'name' => 'Smoke-free property',
            ],
            [
                'id' => 125,
                'sync_id' => 125,
                'locale' => 'en',
                'translation_id' => 125,
                'name' => 'Designated smoking area',
            ],
            [
                'id' => 126,
                'sync_id' => 126,
                'locale' => 'en',
                'translation_id' => 126,
                'name' => 'Facilities for disabled guests',
            ]
        ]);
    }
}
